### ISSUE TITLE
AD icon with magic tank armor bonus not tracked 

### ISSUE THREAD

**Issue by filipagh** [NadyaNayme/BetterBuffsBar#1]
![image](https://github.com/NadyaNayme/BetterBuffsBar/assets/22474494/266e2f01-9470-4120-92e1-772c8d75ad4a)

animate dead is not tracked with BetterBuffs but alt1 can track it 

it happend when you have magic tank armor then icon of buff change 
without magic tank armor AD is tracked OK

**Comment by filipagh** [comment]
i suggest change image compare threshold to 60 i test 70 but it fail sometimes

**Comment by NadyaNayme** [comment]
I'll do some testing actually using it in combat so that I get a proper (arg) for it which will cause the thresholds to change a bit. AD has an issue with lower thresholds in that it would have lots of false positives so I have to dial it in as close as possible.

Also AFK Warden does sometimes lie. It will detect and show the buffs properly when selecting a buff to watch but if you tell it to watch the buff it will fail to actually track it properly. But I do suspect that it is _generally_ more accurate if anything because Skillbert better knows what he is doing. :P 

Thanks for the report though. I'll test it out later today.

**Comment by Horusxav** [comment]
Hey! So did you guys find a solution to this issue? Dealing with this too atm when wearing tank mage armour

**Comment by filipagh** [comment]
@Horusxav i tweak threshold as workaround for this issue, you can use my updated app 

`alt1://addapp/https://filipagh.github.io/BetterBuffsBar-AD-workaround/dist/appconfig.json`

**Comment by Horusxav** [comment]
@filipagh Thank you so much amazing :))

**Comment by filipagh** [comment]
@Horusxav does my fix work for you ?

**Comment by Horusxav** [comment]
@filipagh yep it works perfectly thanks alot :) havent had any issue

**Comment by NadyaNayme** [comment]
I've accepted @filipagh 's PR with the lowered threshold as well - just so you can keep using BBB and receiving future updates rather than having to use a fork to fix an issue with a singular buff.
