### ISSUE TITLE
BOLG spec not working after changes to how it is displayed

### ISSUE THREAD

**Issue by dubudevs** [NadyaNayme/BetterBuffsBar#11]
BOLG stack tracking is currently completely broken, it doesnt work with any combination of settings.

BOLG has a single buff with a number on it now that goes from 0-3 or 0-7 stacks (0 being blank/no number shown), there are no longer 2 buffs. Is it possible to implement this, and have the "big" version have the number large in the middle? https://i.imgur.com/Gsh6r40.png Like this but obviously saturated.

**Comment by dubudevs** [comment]
Correction, its 2 buffs, but the buffs are different than they used to be and are displayed differently. 

https://github.com/user-attachments/assets/ed2f9369-34dc-481a-b5fa-7b54992366ce

**Comment by NadyaNayme** [comment]
Yea this is due to there being 3 versions of the BOLG buff and I haven't had time to unfuck things. There's the pre-beta manual splitting of the single buff that used to be spec+stacks and then there's the beta-code for the red/green stacks buff and reading the split spec buff. I need to delete both special handling codes and just make it a normal buff like every other buff.

I know what the issue is and its mostly just removing all the special BOLG-handling code now that the spec + stacks are 2 separate buffs and the stacks don't have 2 buffs depending on stacks. 

I'll fix it as soon as I get time to do so - I just haven't really had the time and have been deep in other projects as of late. 

With T100's and Elite Drakolith armour making BOLG see a resurgence in use I'll try and prioritize this as more and more people will be encountering this issue trying to use BBB w/ BOLG.

**Comment by dubudevs** [comment]
Thanks for your reply, and thanks for your work on the app :) If only they used their brain on how the buff design should be handled when the wep came out, but I guess we are talking about jagex here.

**Comment by NadyaNayme** [comment]
I really hope I didn't fuck anything up while untangling that mess.

Note that due to how buffs/time is detected and me really not wanting to add too much special error handling - having 0 stacks will appear as inactive for PE stacks. So it only shows 1-7 stacks and not the active-but-empty 0 stack buff because really that shouldn't even be a thing (shame on Jagex). 

![image](https://github.com/user-attachments/assets/f2c6dcc3-ca37-4739-ab49-8f2afb8b96be)


In addition - I wouldn't recommend using the Overlay w/ BOLG. It's too delayed to be meaningful. This is something I'm hoping to improve when I can sit down and rewrite BBB to draw the overlay better. Although that's unlikely to be anytime this year. It should be near-instant within the app window.
