### ISSUE TITLE
Living Death cooldown icon persists

### ISSUE THREAD

**Issue by Jhaego** [NadyaNayme/BetterBuffsBar#2]
The icon for Living Death's cooldown persists, meaning if never disappears and stays at 2 seconds despite "Fade Inactive Buffs" being disabled. I tried multiple times. 

it's obviously not a big issue, but I do like a clean UI

![Runeapps Alt1_3NDdO2FLR7](https://github.com/NadyaNayme/BetterBuffsBar/assets/62746266/0fea80a4-20f1-439f-a743-ebb3caa5a698)

**Comment by NadyaNayme** [comment]
The "Fade Inactive Buffs" isn't terribly well tested and actually shouldn't be showing cooldown timers at all. 

I probably won't have time to look into this until the weekend but I'll give it a look. Thanks for the bug report.

**Comment by Jhaego** [comment]
ahhh, I see, that makes sense. no worries and no rush whatsoever. 

is Github the best way for you to receive bug-reports etc. in the future, assuming I think of more?

I'm happy to help, in this small way. one of my biggest issues with the game has been, and is, that buffs are an absolute pain to keep track of since there is no in-game way of sorting nor disabling them individually.... in summary, this plugin is very promising for me in regard to improving game quality; thank you very much.

**Comment by NadyaNayme** [comment]
Discord or Github are both fine. Same name on Discord.

Regarding the setting though - would you prefer if cooldowns were shown on the bar or actually hidden when not on the buff bar? I know a lot of people were fans of the fading buffs vs disappearing so I don't have a lot of feedback on how people would prefer the disappearing buffs to work when it comes to tracking cooldowns. Even though I intended it to not show cooldowns if the people using it would prefer it still did its an easy enough change to make.

**Comment by Jhaego** [comment]
Gotcha, thank you.

that is an excellent question. I *think* I would prefer Cooldowns **not** being shown on the buffbar. I'll happily look at my good old ability bar to check on a cooldown. this option - hiding cooldowns - might also be easier to implement and less prone to errors?

maybe I should've added this as an additional Issue on Github, but: I was pvm'ing with a friend, me using necro & him using range, and all of a sudden my BetterBuffBar started showing Death's Swiftness - it never disappered from the bar so I had to disable Swiftness in the plugin settings. (My intention/hope is to use BetterBuffBar for all 4 combat styles without changing settings.)

**Comment by NadyaNayme** [comment]
I opened an issue #3 for the other one. 

> (My intention/hope is to use BetterBuffBar for all 4 combat styles without changing settings.)

This is generally not the recommended way as all buffs are scanned for all the time to see if they are active. This can hurt performance and increase the small delay present. For best performance you only want to track the buffs you care about at that time.

I have plans for a "profiles" system to make swapping tracked/untracked buffs easier. So you could swap from your "melee" buffs to your "ranged" buffs more easily. But that won't be coming until after I've refactored my plugins.

**Comment by Jhaego** [comment]
super.

ah, that makes sense altho I understand nothing about what is going on under the hood; I'll stick to using it for one combat style for now.

implementing Profiles sounds like a fantastic solution. no rush. thank you for your time, much appreciated.

**Comment by NadyaNayme** [comment]
Without getting too technical - every buff on your buff bar is compared vs an image of a tracked buff. If it is found I capture its data, stop the loop early for that buff, and display it in the overlay. But if a buff will never be active on your buff bar and you're leaving it as tracked - I'm scanning your entire buff bar trying to match a buff that will never match. Scans are done 3 times per game tick (roughly) since I can't easily sync with game ticks. So if you have 25 active buffs and are scanning 5 buffs that will never match - I'm scanning 25x5 times about 5 times a second: so 625 scans are being done for no reason as they'll never be matched on.

Alt1's image comparison is pretty quick (as are computers) so I'm not entirely sure how much of an issue this is in practice. It really depends how efficient Alt1's image comparison is. It could be it isn't an issue at all or would only become an issue if I was doing it 100,000's of times a second instead of 1000~ times a second. After refactoring I do have plans to run some benchmarks to see if it even matters or not but out of an abundance of caution my current recommendation is to move buffs you don't care to track to Untracked so that they don't get scanned for.

**Comment by Jhaego** [comment]
righto, that does sound unnecessarily rough for my poor laptop. might as well save it some resources. benchmarks on performance impacts would be interesting to see. 

the short explanation was appreciated, interesting stuff. if you ever happen to need a tester or something I'll happily be of service; I'm 'frakkefyr' on Discord.

**Comment by NadyaNayme** [comment]
I think I solved the issue. While Necro Job Gauge is only delayed 1 tick for some reason BBB seems to be delayed between 2-3 ticks. This extra delay is what breaks the cooldown tracking - as the 1s remaining is never being read by BBB due to the delay.

The new setting for Overlay Delay Compensation should actually fix this problem if set to 1s or 2s. This will kick off the cooldown 2s earlier which should cause it to work properly now.

Haven't had an opportunity to test if it fixed this issue since I only just added the setting today - but going to give it a test when I can as I believe that was the problem.

**Comment by NadyaNayme** [comment]
Haven't had this problem since I reworked how the cooldowns are managed. There is a problem with cooldowns not starting if your overlay compensation is set too high but that's an issue of having the overlay compensation set too high.

So marking this as closed.
