### ISSUE TITLE
Suggestion: Sound alerts

### ISSUE THREAD

**Issue by sparers** [NadyaNayme/BetterBuffsBar#8]
Hello,

First of all, I want to thank you for the amazing work you did with this plugin. I just wonder if there are any plans to introduce sound alerts. Thank you in advance.

**Comment by NadyaNayme** [comment]
There is not. Primarily because any buff worth sounding an alarm over is something AFKWarden can track and sound an alarm for making the functionality a bit redundant. But also because any false negatives, which still happen often enough, would mean sounding an alarm making it more annoying than useful.

If I ever approach >99% reliability instead of the >95%~ or so I have now I might add sound alerts in the future. But I don't expect things will ever be reliable enough unless Jagex gets rid of transparent buffs for ones with actual backgrounds. 

I'm more of a fan of composing several purpose-specific tools together rather than having one tool that tries to do everything but does everything poorly. If you want alarms - AFKWarden is probably the better tool to use as it's built for that purpose.
